GET http://localhost:8080/api/todos
###

POST http://localhost:8080/api/todos
Content-Type: application/json

{
    "title": "Jogging",
    "detail": "Do a 5km jogging at Suvannabhumi Airpot Happy and Healthy Bike Lane"
}
###

POST http://localhost:8080/api/todos
Content-Type: applocation/application/json

{
    "title": "Tiktok brainrot",
    "detail": "To much tung tung tung tung tung tung sahur could melt your brain."
}
###

PUT http://localhost:8080/api/todos/4
Content-Type: application/json

{
    "title": "Drink sparkling alcohol",
    "detail": "As a celebration of my RestAPI with SwaggerUI, it's time to cheers"
}
###

DELETE http://localhost:8080/api/todos/2
###

DELETE http://localhost:8080/api/todos/0
###

PUT http://localhost:8080/api/todos/3
Content-Type: application/json

{
    "title": "Tiktok brainrot",
    "detail": "To much tung tung tung tung tung tung sahur could melt your brain.",
    "status": true
}
###